dart-lang/args

- .analysis_options
- .travis.yml
- analysis_options.yaml
- example/test_runner.dart
- lib/command_runner.dart
- lib/src/arg_parser.dart
- lib/src/arg_parser_exception.dart
- lib/src/arg_results.dart
- lib/src/help_command.dart
- lib/src/option.dart
- lib/src/parser.dart
- lib/src/usage_exception.dart
- test/args_test.dart
- test/command_runner_test.dart
- test/command_test.dart
- test/parse_test.dart
- test/usage_test.dart
- test/utils.dart
> Enable Travis-CI

- lib/command_runner.dart
> Document that Command.argParser can be overridden.

- CHANGELOG.md
- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- lib/src/parser.dart
- pubspec.yaml
- test/allow_anything_test.dart
> Add ArgParser.allowAnything().

- .travis.yml
- CHANGELOG.md
- README.md
- lib/src/arg_parser.dart
- pubspec.yaml
- test/parse_test.dart
- test/trailing_options_test.dart
Also release 1.0.0.
Closes #65
> Make allowTrailingOptions default to `false`.

- CHANGELOG.md
- lib/src/arg_parser.dart
- pubspec.yaml
> Fix a fuzzy arrow warning

- CHANGELOG.md
- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- lib/src/option.dart
- pubspec.yaml
> Take Iterables rather than Lists where possible

- CHANGELOG.md
- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- pubspec.yaml
> Type the callback parameter to addOption as Function

- CHANGELOG.md
- lib/command_runner.dart
- pubspec.yaml
> Type Command.run()'s return value as FutureOr<T>

- CHANGELOG.md
- pubspec.yaml
> Narrow the SDK constraint to require FutureOr

- CHANGELOG.md
- lib/src/usage.dart
- pubspec.yaml
- test/usage_test.dart
> Display the default values for options with allowedHelp specified

- pubspec.yaml
pubspec conventions dart-lang/site-www#825
> pubspec conventions dart-lang/site-www#825

- .travis.yml
- analysis_options.yaml
- example/test_runner.dart
- lib/command_runner.dart
- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- lib/src/arg_parser_exception.dart
- lib/src/arg_results.dart
- lib/src/option.dart
- lib/src/parser.dart
- lib/src/usage.dart
- pubspec.yaml
- test/allow_anything_test.dart
- test/args_test.dart
- test/command_parse_test.dart
- test/command_runner_test.dart
- test/command_test.dart
- test/parse_test.dart
- test/test_utils.dart
- test/trailing_options_test.dart
- test/usage_test.dart
- test/utils_test.dart
Improves the package health when analyzed on the pub site
> Enable and fix a number of standard lints and deprecated member use

- CHANGELOG.md
- README.md
- codereview.settings
Remove superfluous codereview.settings
> Fix deprecated URLs

- CHANGELOG.md
- pubspec.yaml
> prep for publishing 1.5.3

- CHANGELOG.md
- README.md
- pubspec.yaml
> Update http URLs to https

- test/test_utils.dart
As of Dart 2.1, Future/Stream have been exported from dart:core.
> Remove unused dart:async imports.

- README.md
I've submitted this PR to replace #127 as that PR has languished do to a the lack of a contributor signoff.
> improved the doco on the CommandRunner

- lib/command_runner.dart
Use the `!` at the point where it is assigned rather than on every
reference.
> Make a local variable non-nullable

- .travis.yml
- CHANGELOG.md
- lib/command_runner.dart
- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- lib/src/arg_parser_exception.dart
- lib/src/arg_results.dart
- lib/src/help_command.dart
- lib/src/option.dart
- lib/src/parser.dart
- lib/src/usage.dart
- lib/src/utils.dart
- pubspec.yaml
- test/allow_anything_test.dart
- test/args_test.dart
- test/command_parse_test.dart
- test/command_runner_test.dart
- test/command_test.dart
- test/parse_test.dart
- test/test_utils.dart
- test/trailing_options_test.dart
- test/usage_test.dart
- merges the null safety branch into master
- this isn't ready yet, but further development will happen on the master branch
This migration never received a review afaict, so it needs one at this time.
> Migrate to null safety

- CHANGELOG.md
- lib/command_runner.dart
- pubspec.yaml
Also tweaked a couple of tiny things.
I will Git tag this and roll it into the SDK but not publish until things look good after that.
> Bump to 2.0.0 in anticipation of release.

- CHANGELOG.md
- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- test/parse_test.dart
> Give a specific function type for callback

- lib/src/allow_anything_parser.dart
- lib/src/arg_parser.dart
- lib/src/arg_results.dart
- lib/src/option.dart
- lib/src/parser.dart
- test/allow_anything_test.dart
- test/args_test.dart
> Deprecate methods name get*

- .github/workflows/test-package.yml
> Use latest setup action

- CHANGELOG.md
- pubspec.yaml
- test/command_parse_test.dart
This prepares for landing https://dart-review.googlesource.com/c/sdk/+/190360 into the analyzer.
> Fix pre-existing HintCode.UNNECESSARY_TYPE_CHECK_TRUE

- README.md
As title, correcting a code snippet.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a …
> Add missing curly braces in README.md

- .github/workflows/test-package.yml
- CHANGELOG.md
- pubspec.yaml
- rev to `2.5.0` and prep to publish
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a …
> rev to 2.5.0 and prep to publish
