dart-lang/args

lib/src/arg_parser.dart
lib/src/arg_results.dart
lib/src/option.dart
pubspec.yaml

`args` was using `package:collection/wrappers.dart` for creating unmodifiable collection views, but this functionality is built directly into the SDK in `dart:collection`
This would be a breaking change, because of transitive dependencies.

Remove dependency on 'collection'

---

README.md

Noticed this on the docs, but the README hadn't been updated yet.
```
@Deprecated("Replaced with get usage. getUsage() will be removed in args 1.0")
String getUsage() => usage;
```

replace deprecated getUsage() method

---

CHANGELOG.md
README.md
lib/args.dart
lib/command_runner.dart
lib/src/arg_parser_exception.dart
lib/src/parser.dart
pubspec.yaml
test/command_runner_test.dart

This now prints the usage for the command that failed to parse, rather
than always printing the root usage.
Closes #52

Print the proper usage in CommandRunner.

---

CHANGELOG.md
lib/command_runner.dart
pubspec.yaml
test/command_runner_test.dart

Print command help for "bin --help command"

---

CHANGELOG.md
lib/command_runner.dart
lib/src/help_command.dart
pubspec.yaml
test/command_runner_test.dart
test/utils.dart

This was unintentionally supported prior to 0.13.6+1. This re-adds
support, documents and tests it, and adds type annotations to make it
type-safe.
Closes #57
Closes #58

Support command return value forwarding.

---

.travis.yml
CHANGELOG.md
analysis_options.yaml
example/test_runner.dart
lib/src/allow_anything_parser.dart
lib/src/arg_parser.dart
lib/src/option.dart
pubspec.yaml
test/args_test.dart
test/command_runner_test.dart
test/command_test.dart
test/parse_test.dart
test/usage_test.dart

This allows us to be more specific in our types and to keep flags that are
specific to multi-options in the place where they make sense.
Closes #90

Add a separate addMultiOption() method

---

CHANGELOG.md
lib/src/usage.dart
pubspec.yaml
test/usage_test.dart

We were printing the option list, with square brackets, even for
options that didn't have a default.
Fixes dart-lang/test#774.

Fix addMultiOption() and addOption(allowMultiple) usage

---

analysis_options.yaml

Many of these aren't passing, and I don't believe in supporting lints that are generally unmaintained and non-canonical.

Remove lints

---

.travis.yml
example/test_runner.dart
lib/command_runner.dart
lib/src/allow_anything_parser.dart
lib/src/arg_parser.dart
lib/src/arg_results.dart
lib/src/help_command.dart
lib/src/option.dart
lib/src/parser.dart
lib/src/usage.dart
lib/src/usage_exception.dart
pubspec.yaml
test/allow_anything_test.dart
test/command_runner_test.dart
test/command_test.dart
test/parse_test.dart
test/test_utils.dart
test/trailing_options_test.dart
test/usage_test.dart
test/utils_test.dart

- always_declare_return_types
- annotate_overrides
- prefer_conditional_assignment
- prefer_if_null_operators
- prefer_single_quotes
- prefer_spread_collections
- unnecessary_this
- use_function_type_syntax_for_parameters
Bump min SDK to 2.3.0 to allow spreads in collection literals.
Drop unused author field from pubspec.
Restructure a string to avoid a line over 80 characters.

Fix newly enforced package:pedantic lints

---

CHANGELOG.md
lib/src/allow_anything_parser.dart
lib/src/arg_parser.dart
lib/src/parser.dart
test/parse_performance_test.dart

Add a test that checks that parse time does not increase more than 30x when input size grows from 10k to 100k. The current increase is about x2, so this is a very loose check that should be reliably green. It will only trigger if we hit O(n^2) behaviour again.

Fix performance issues due to list.removeAt(0), which makes parsing O(n^2).

---

CHANGELOG.md
lib/command_runner.dart
test/allow_anything_test.dart
test/test_utils.dart

Address an issue when using `ArgParser.allowAnything()` with `CommandRunner`:
- No longer automatically add a 'help' option to commands that don't validate
their arguments
- fix https://github.com/dart-lang/args/issues/123 (a slight variant of the PR https://github.com/dart-lang/args/pull/124)
The CommandRunner class currently doesn't work well with Commands that use an ArgParser.allowAnything() parser; this PR addresses that. It'll allow for subcommands that can do things like just delegate all arg parser (and execution) to another entity, like a subprocess.

address an issue when using ArgParser.allowAnything() with CommandRunner

---

CHANGELOG.md
lib/src/parser.dart
test/parse_performance_test.dart

Hi Jake,
I was on the fence on whether this is worth sending; for 50k inputs, which is about the max we'll realistically see, we're looking at 5-9ms gain. That's just a little bigger than noise. WDYT?
```
50k short flags
before: 11ms, 11ms, 13ms, 11ms, 17ms
after: 6ms, 5ms, 6ms, 5ms, 8ms
50k abbreviations
before: 97ms, 114ms, 120ms, 111ms, 107ms
after: 39ms, 37ms, 51ms, 36ms, 36ms
50k long flags
before: 27ms, 26ms, 24ms, 24ms, 28ms
after: 15ms, 19ms, 19ms, 15ms, 15ms
50k long options with =
before: 27ms, 26ms, 27ms, 24ms, 26ms
after: 15ms, 19ms, 19ms, 15ms, 15ms
```
Thanks.

Faster parsing

---

CHANGELOG.md
lib/src/arg_parser.dart
pubspec.yaml

Closes #134
The `addCommand` API is a little confusing, it doesn't impact the usage
string the way you might expect.
In the future we might consider hiding this API, for now call out the
confusing aspect and point to the API that most folks should use.

Reference CommandRunner from addCommand docs

---

CHANGELOG.md
lib/src/usage.dart
pubspec.yaml
test/usage_test.dart

Fixes #48
The extra blank lines imply a grouping, however the grouping is
arbitrary based on which options happened to wrap, and may vary based on
the terminal width. Instead keep all options without extra newlines.

Remove extra blank lines between options

---

CHANGELOG.md
lib/src/help_command.dart
pubspec.yaml
test/command_runner_test.dart

Closes #131
The `help` command is redundant against the bottom line of the usage
text which explains how to use help in a more understandable way.

Remove help from the list of commands in usage

---

lib/args.dart
lib/src/arg_results.dart
lib/src/option.dart

- Note some argument restrictions when `name` must be a valid option.
- Remove a comment that adds no information on a constructor.
- Use a consistent pattern for checking valid option names -
`containsKey` rather than check for a `null` value.
- End a doc comment with a period.
- Change a getter doc comment to a noun phrase.
- Remove some repetitive details from doc comments, like types.
- Add explicit `show` to all exports rather than rely on catching all
package private stuff with a `hide`.
- Use `.toSet()` over `Set.from` to copy a set.

Clean up some doc comments and code style

---

.travis.yml
pubspec.yaml
test/allow_anything_test.dart
test/args_test.dart
test/parse_test.dart
test/usage_test.dart

* update sdk constraints and deps
* remove experiment flags from CI
* fix some tests
Note that I had already pushed an update to bump the version to 2.0.0-nullsafety. Feel free to push back on that here.

null safety cleanup

---

test/test_utils.dart

- Use `having` chain from the `TypeMatcher` rather than wrap in a
predicate with calls to `expect`.
- Add static types to arguments.
- Switch from `TypeMatcher` constructor to `isA` method.

Simplify throwsUsageException matcher util

---

lib/command_runner.dart

Avoids the need for an unreachable `return null;` and a nullable return
type.

Make command.usageException return Never

---

lib/src/help_command.dart

This may make it easier to understand choices around nullability by
making it explicit that the help command can never return a useful value
from it's `run` method.
Remove the unnecessary return value and return statement since a `Null`
return type may be treated similarly to `void`.

Use Null as return type for HelpCommand.run

---

CHANGELOG.md

This package could have more [Pub points](https://pub.dev/packages/args/score) if we fix this issue:
> Links in `CHANGELOG.md` should be secure. 1 link is insecure.

Fix link to use https

---

lib/args.dart

This was hidden in #147 but it is used by some external packages and
there is no strong reason to make this an additional breaking change.

Re-expose the class OptionType

---

lib/src/arg_parser.dart
lib/src/usage.dart

- Add a top level method rather than require a constructor call and call
to `generate()` when there is otherwise no reason to hold on to the
`Usage` object. This makes it more clear that the implementation is
following a method object pattern.
- Update doc comment which had drifted from the original implementation
and no longer referred to the correct arguments.
- Make the `StringBuffer` field final since it is now a guaranteed
single use object.
- Make everything possible private. This revealed that there was a field
being updated but never read and can be removed.
- Remove `get` from method names.
- Make the `_columnWidths` late final rather than initialize it manually
in the call to `generate()`.
- Pull out sub-methods `_writeSeparator` and `_writeOption` from
`generate` to reduce …

Refactor usage.dart

---

CHANGELOG.md
lib/src/allow_anything_parser.dart
lib/src/arg_parser.dart
lib/src/option.dart
lib/src/parser.dart
pubspec.yaml
test/args_test.dart
test/parse_test.dart

Closes https://github.com/dart-lang/args/issues/181
Add `aliases` named argument to `addFlag`, `addOption`, and `addMultiOption`, as well as a public `findByNameOrAlias` method on `ArgParser`. This allows you to provide aliases for an argument name, which eases the transition from one argument name to another.
Keys are _not_ added to the `options` map for each alias.
cc @Hixie

Add support for argument name aliases

---

analysis_options.yaml
lib/src/usage.dart
lib/src/utils.dart
test/command_runner_test.dart
test/command_test.dart
test/parse_test.dart
test/trailing_options_test.dart

Gives some safety against mistakes since there are fewer calls on a
statically dynamic variable.

Enable lint prefer_typing_uninitialized_variables

---

lib/src/parser.dart

Each of the methods `parseSoloOption`, `parseAbbreviation`, and
`parseLongOption` do some string manipulation and checking, before
potentially calling the same method on their parent parser. No state
changes during parsing part. Split out a 'handle' method in each case
that takes a partially parsed result as arguments, and avoid duplicating
that work at each step in the parent chain. There may be other work that
could be avoided but it would take deeper refactoring. The
`parseShortFlag` does not need to be split since there are no
intermediate results computed from the String.
Change all possible members of `Parser` to private.

Split parse* methods to avoid duplicate work

---

CHANGELOG.md
pubspec.yaml

This releases the `aliases` and `mandatory` features for options.

publish 2.1.0

---

CHANGELOG.md
lib/src/parser.dart
pubspec.yaml
test/command_runner_test.dart

Fixes https://github.com/dart-lang/args/issues/197
The 2nd argument to ArgParserException is supposed to be the command chain that it was parsed from and not the option (note this is handled separately as well) - this was causing the command runner to throw a null assertion error later on by passing the name of the mandatory option as the command name, which doesn't exist as a command.

fix a null assertion error when there are missing mandatory args in commands

---

CHANGELOG.md
lib/command_runner.dart
pubspec.yaml
test/command_runner_test.dart
test/test_utils.dart

Fixes https://github.com/dart-lang/args/issues/201
Uses the [Optimal string alignment distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance#Optimal_string_alignment_distance) algorithm to compute edit distance, which allows for additions, removals, substitutions, and swaps - all as 1 cost operations.
Suggests any commands within an edit distance of <=2, ~although we should possibly make this configurable~ which is now configurable.
We should also consider whether this should be opt in - it is likely to break existing integration tests in some cases. ~We could also consider adding in an opt out mechanism.~ you can now opt out by setting the distance to zero.

show similar commands with an edit distance of 2 or less

---

CHANGELOG.md
lib/command_runner.dart
pubspec.yaml
test/command_runner_test.dart
test/test_utils.dart

To enable https://github.com/flutter/flutter/issues/83706
Formatting is loosely based on what `Brew` does, and open to suggestions.  Existing tests are unchanged.
Example (all displayed commands categorized):

Add ability to group commands by category in usage

---

analysis_options.yaml
lib/command_runner.dart
lib/src/arg_parser.dart
lib/src/help_command.dart
lib/src/option.dart
pubspec.yaml
test/command_runner_test.dart
test/parse_performance_test.dart

Fix existing violations of lints:
- `prefer_initializing_formals`
- `unnecessary_string_interpolations`
- `prefer_function_declarations_over_variables`
Ignore one case of `prefer_void_to_null` to work around
https://github.com/dart-lang/linter/issues/2792

Move from pedantic to lints package

---

CHANGELOG.md
README.md
analysis_options.yaml
pubspec.yaml

prep to publish 2.3.1:
- rev tp 2.3.1
- update the changelog
- add markdown badges to the readme

prep to publish 2.3.1

---

.github/workflows/publish.yaml
CHANGELOG.md
lib/command_runner.dart
pubspec.yaml
test/command_runner_test.dart
test/test_utils.dart

Also introduce a concept of suggestionAliases (alternative names that cannot be used as a command name, but they will be used for suggesting the actual command).
The motivation comes from this suggestion: https://github.com/dart-lang/sdk/issues/50971#issuecomment-1412495274
That would allow us to give a good suggestion if someone writes `dart packages get` -> `Did you mean pub?`.

Suggest command based on aliases

---

CHANGELOG.md
CONTRIBUTING.md
README.md
pubspec.yaml

- update the readme to remove info about the publishing automation
- add a contributing doc (taken from `dart-lang/.github`; updated w/ publishing info

update readme; add contributing doc

---

CHANGELOG.md
pubspec.yaml

- added package topics to the pubspec file

added package topics to the pubspec file

---

CHANGELOG.md
README.md
lib/src/arg_results.dart
lib/src/parser.dart
pubspec.yaml
test/command_runner_test.dart
test/parse_test.dart

- change the validation of `mandatory` options; perform validation when the value is retrieved (from the `ArgResults` object), instead of when the args are parsed
- fix https://github.com/dart-lang/args/issues/245
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#mak …

adjust the validation of mandatory options

---

.github/workflows/test-package.yml
CHANGELOG.md
analysis_options.yaml
example/command_runner/draw.dart
lib/command_runner.dart
pubspec.yaml
test/command_runner_test.dart

- switch to using package:dart_flutter_team_lints
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart …

switch to using package:dart_flutter_team_lints

---

CHANGELOG.md
lib/src/arg_parser_exception.dart
lib/src/arg_results.dart
lib/src/parser.dart
pubspec.yaml
test/command_parse_test.dart
test/command_runner_test.dart
test/parse_test.dart
test/test_utils.dart
test/trailing_options_test.dart

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
Although ArgParserException inherits from FormatException, the source is always null.
This is a very small fix, but please let me know if testing is needed.
---
<details>
- Most changes should add an …

Added arg argument when throwing a `ArgParserException`.
